version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
    working_dir: /app
    user: appuser
    command: ./gradlew --project-cache-dir /tmp/gradle-cache bootRun
